// types
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Tommy | Portfolio',
  description: 'Generated by NextJS, Tailwind and Shadcn'
}

export default function Home() {
  return (
    <div>
      <p>Portfolio | Home</p>
    </div>
  )
}
