// types
import type { Metadata } from 'next'

// components
import { Container } from '@/components/ui/container'
import { GridLine, GridLineWrapper } from '@/components/ui/gridLine'
import { Section } from '@/components/ui/section'
import { ContactButton } from '@/components/section/home/contactButton'

export const metadata: Metadata = {
  title: 'Tommy | Portfolio',
  description: 'Generated by NextJS, Tailwind and Shadcn'
}

export default function Home() {
  return (
    <div>
      <Section className='space-y-4' id='hero'>
        <GridLine position='top' />
        <Container>
          <div className='flex flex-col gap-4 py-8'>
            <GridLineWrapper className='col-span-2 sm:col-span-3'>
              <p className='whitespace-nowrap text-sm font-medium md:text-base'>
                Full Stack Developer · Dublin{' '}
                <span className='hidden sm:inline-block'>· Tommy</span>
              </p>
            </GridLineWrapper>
            <GridLineWrapper className='col-span-2 sm:col-span-4 lg:col-span-3'>
              <h1 className='text-4xl font-semibold sm:text-5xl lg:leading-[3.5rem]'>
                Hey there, I&apos;m Tommy! A full stack developer from Ireland
              </h1>
            </GridLineWrapper>
            <GridLineWrapper className='col-span-3 lg:col-span-2'>
              <p className='text-muted-foreground sm:text-lg'>
                Currently I&apos;m working as a full time firefighter /
                paramedic while pursuing my passion in tech and web development.
              </p>
            </GridLineWrapper>
            <GridLineWrapper className='col-span-1 xs:col-span-2 sm:col-span-4 md:col-span-3'>
              <div className='flex flex-col gap-2 sm:flex-row sm:items-center'>
                <p className='text-xs xs:text-sm sm:text-base'>
                  Want to get started? See more below or
                </p>
                <ContactButton />
              </div>
            </GridLineWrapper>
          </div>
        </Container>
        <GridLine position='bottom' />
      </Section>{' '}
    </div>
  )
}
