// types
import type { Metadata } from 'next'

// components
import Image from 'next/image'
import { ToastButton } from '@/components/display/toast'
import { ThemeButton } from '@/components/display/theme'
import { LinkButton } from '@/components/display/link'

export const metadata: Metadata = {
  title: 'Shadcn | Starter',
  description: 'Generated by NextJS, Tailwind and Shadcn'
}

export default function Home() {
  return (
    <div className='grid min-h-screen grid-rows-[20px_1fr_20px] items-center justify-items-center gap-16 p-8 pb-20 sm:p-20'>
      <main className='row-start-2 flex flex-col items-center gap-8 sm:items-start'>
        <Image
          className='dark:invert'
          src='https://nextjs.org/icons/next.svg'
          alt='Next.js logo'
          width={180}
          height={38}
          priority
        />
        <ol className='list-inside list-decimal text-center text-sm sm:text-left'>
          <li className='mb-2'>
            Get started by editing{' '}
            <code className='rounded bg-black/[.05] px-1 py-0.5 font-semibold dark:bg-white/[.06]'>
              src/app/page.tsx
            </code>
            .
          </li>
          <li>Save and see your changes instantly.</li>
        </ol>

        <div className='flex flex-col items-center gap-4 sm:flex-row'>
          <ToastButton message='Hello, World!'>Get started</ToastButton>
          <ThemeButton />
        </div>
      </main>
      <footer className='row-start-3 flex flex-wrap items-center justify-center gap-6'>
        <LinkButton>Learn</LinkButton>
        <LinkButton>Examples</LinkButton>
        <LinkButton>Docs</LinkButton>
      </footer>
    </div>
  )
}
